version: '3.8'
services:
  service-db:
    image: postgres:16.0-bookworm
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped